name: Continues Integration
on:
  workflow_dispatch:
jobs:
  prcheck:
    runs-on: ubuntu-latest

    steps:       
      - name: Create folder for frontend
        run: 'sudo mkdir /su_frontend'
        
      # name: Checkout
      #  uses: actions/checkout@v3
        
      - name: Use custom node version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Node version
        run: "node --version"
        
      #- name: Checkout frontend repo TeachUAClient
      #  uses: actions/checkout@v4
      #  with:
      #    repository: ita-social-projects/TeachUAClient
      #    ref: develop
      
      #- name: Fix env vars
      #  run: echo "PUBLIC_URL=/dev" >> .env.production  

      #- name: Install dependencies
      #  run: "npm install --legacy-peer-deps"
      #  continue-on-error: true

      #- name: Build frontend
      #  run: "CI=false npm run build"
        
      #- name: copy frontend to frontend folder
      #  run: 'sudo cp -r build/* /su_frontend'
        
      - name: Checkout backend repo ci560
        uses: actions/checkout@v4
        with:
          repository: softservedata/ci560
          ref: main
          
      #- name: Inject frontend
      #  run: 'sudo cp -r /su_frontend/* src/main/resources/frontend'

      - name: Java version
        run: "java -version"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Java version
        run: "java -version"

      - name: Build project
        # run: 'mvn package -DskipTests -Dcheckstyle.skip'
        run: 'mvn package -DskipTests -Dcheckstyle.skip'

      - name: Run Unit Tests
        run: 'mvn package -Dcheckstyle.skip'

      #- name: Copy results to the remote host over SSH
      #  uses: appleboy/scp-action@master
      #  with:
      #    host: ${{ secrets.HOST }}
      #    username: ${{ secrets.USER }}
      #    key: ${{ secrets.SSH_PRIVATE_KEY }}
      #    port: ${{ secrets.PORT }}
      #    source: "target/dev.war"
      #    target: "/opt/tomcat/latest/webapps/"
      #    strip_components: 1
          
      #- name: Change permissions to tomcat user
      #  uses: garygrossgarten/github-action-ssh@release
      #  with:
      #    command: chown -R tomcat:tomcat /opt/tomcat
      #    host: ${{ secrets.HOST }}
      #    username: ${{ secrets.USER }}
      #    privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
 
